import { chromium } from 'playwright';
const base = 'http://localhost:3000';
const api = 'http://localhost:3001/api/v1';
const login = await fetch(`${api}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: 'admin@elwataniya.com', password: 'Admin@123' }) }).then((r) => r.json());
const token = login?.data?.accessToken;
const browser = await chromium.launch();
const ctx = await browser.newContext();
const page = await ctx.newPage();
const logs = [];
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') logs.push(`[console.${m.type()}] ${m.text().slice(0, 300)}`); });
page.on('pageerror', (e) => logs.push('[pageerror] ' + String(e).slice(0, 500)));
await page.goto(base + '/ar/logout', { waitUntil: 'domcontentloaded' }).catch(() => {});
await page.goto(base, { waitUntil: 'domcontentloaded' });
await page.evaluate((t) => { localStorage.setItem('elwataniya_access_token', t); document.cookie = `elwataniya_token=${t};path=/;SameSite=Lax;max-age=604800`; }, token);
await page.goto(base + '/ar/projects', { waitUntil: 'domcontentloaded', timeout: 90000 });
await page.waitForTimeout(6000);
const overlayText = await page.evaluate(() => {
  const el = document.querySelector('nextjs-portal');
  return el ? (el.shadowRoot ? el.shadowRoot.innerHTML.slice(0, 1000) : el.innerHTML.slice(0, 1000)) : '(no overlay)';
});
console.log('OVERLAY:', overlayText.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').slice(0, 400));
console.log(logs.join('\n'));
await browser.close();