export enum UserRole {
  CEO = 'CEO',
  TECHNICAL_OFFICE = 'TECHNICAL_OFFICE',
  ACCOUNTANT = 'ACCOUNTANT',
  SITE_ENGINEER = 'SITE_ENGINEER',
  STORE_MANAGER = 'STORE_MANAGER',
  EMPLOYEE = 'EMPLOYEE',
}
