-- Align Statement / StatementItem / Payment with frontend extract & payment store

ALTER TABLE "Statement" ADD COLUMN IF NOT EXISTS "runningNumber" INTEGER;
ALTER TABLE "Statement" ADD COLUMN IF NOT EXISTS "label" TEXT;
ALTER TABLE "Statement" ADD COLUMN IF NOT EXISTS "insurancePercent" DECIMAL(12,2) NOT NULL DEFAULT 5;
ALTER TABLE "Statement" ADD COLUMN IF NOT EXISTS "extractDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Statement" ADD COLUMN IF NOT EXISTS "previousPaid" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "Statement" ADD COLUMN IF NOT EXISTS "totalWorkValue" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "Statement" ADD COLUMN IF NOT EXISTS "totalDeductions" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "Statement" ADD COLUMN IF NOT EXISTS "netPayable" DECIMAL(12,2) NOT NULL DEFAULT 0;

ALTER TABLE "StatementItem" ADD COLUMN IF NOT EXISTS "itemCode" TEXT NOT NULL DEFAULT '';
ALTER TABLE "StatementItem" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL DEFAULT '';
ALTER TABLE "StatementItem" ADD COLUMN IF NOT EXISTS "unit" TEXT NOT NULL DEFAULT '';
ALTER TABLE "StatementItem" ADD COLUMN IF NOT EXISTS "contractQuantity" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "StatementItem" ADD COLUMN IF NOT EXISTS "totalQuantity" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "StatementItem" ADD COLUMN IF NOT EXISTS "executionPercent" DECIMAL(12,2) NOT NULL DEFAULT 100;

ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "buildingId" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "contractorId" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "Payment" ALTER COLUMN "statementId" DROP NOT NULL;
